#!/bin/sh
#
# DIARY_INSTALL need to be set
#

if [ -z "$DIARY_INSTALL" ]; then
    echo "DIARY_INSTALL is missing"
    exit 1
fi

if [ -z "$prog" ] ; then
    prog=$0
fi

if [ "$1" = "-h" -o "$1" = "--help" ] ; then
    cat -v << EOF
Usage:
    $prog                  to edit or create today's content
    $prog DATE_DESCRIPTION to specify a day
    $prog FILE_PATH        edit the file '\$DIARY_ROOT/FILE_PATH'
    $prog -h               show this help

EOF
    sed -n 's/^#=\(.*\)/\1/p' "$DIARY_INSTALL/lib/.common.sh"
    exit 0
fi

diary_file=""
if [ -n "$1" -a -f "$DIARY_ROOT/$1" ] ; then
        read -p "edit file $DIARY_ROOT/$1? (Y/n)" REPLY
        if [ -z "$REPLY" -o "$REPLY" = Y -o "$REPLY" = y ] ; then
            # still need to source common.sh for general setups
            . "$DIARY_INSTALL/lib/.common.sh" || die
            diary_file="$DIARY_ROOT/$1"
        fi
fi

if [ -z "$diary_file" ] ; then
    day_desc="$*" . "$DIARY_INSTALL/lib/.common.sh" || die
    if [ ! -f "$diary_file" ] ; then
        read -p "Create a new file $diary_file? (Y/n)" REPLY
        if [ -z "$REPLY" -o "$REPLY" = Y -o "$REPLY" = y ] ; then
            cat > "$diary_file" <<EOF 
# `LANG=C date -d "$diary_day" +'%Y-%m-%d %A'`
## SCHEDULE
## TODO
## NOTE
EOF
        "$DIARY_INSTALL/diary" git add "$diary_file"
        else
            exit
        fi
    fi
fi

$EDITOR "$diary_file"
