#!/bin/sh

if [ -z "$DIARY_ROOT" ] ; then
    echo "DIARY_ROOT not set"
    exit 1
fi

if [ -z "$DIARY_PANDOC" ] ; then
    DIARY_PANDOC=`which pandoc`
    if [ -z "$DIARY_PANDOC" ] ; then
        echo "Cannnot find pandoc"
        exit 1
    fi
fi

if [ -z "$prog" ] ; then
    prog=$0
fi

if [ -z "$1" -o "$1" = '-h' -o "$1" = '--help' ]; then
cat << EOF
    Collect the diaries and export to a file altogether.
    Exported result also contains markdown files in DIARY_ROOT.

    Usage: $prog -o output-file
           output-file: diary.html, diary.pdf, etc.

    Further argument see documentation of `pandoc`.
EOF
    exit
fi

for i in $DIARY_ROOT/*.md $DIARY_ROOT/[0-9][0-9][0-9][0-9]/[0-9][0-9]/*.md ; do
    if [ -f "$i" ] ; then
        cat "$i"
        echo
    fi
done |
    awk '
    !/^##\s+(SCHEDULE|TODO|NOTE)\s*$/ {
        if($0 ~ /^#\s+/)
            h1=$0;
        else {
            if ($0 ~ /^[^#]\s*\S/) {
                if (h1) {
                    print h1;
                    h1="";
                }
                print;
            } else {
                print;
            }
        }
    }' |
    "$DIARY_PANDOC" $*
